# Generated by Django 5.1.5 on 2025-01-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='gif_url',
            field=models.ImageField(blank=True, null=True, upload_to='exercise_gifs/'),
        ),
    ]
