# Generated by Django 5.1.5 on 2025-01-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_exercise_gif_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='gif_url',
            new_name='gif',
        ),
    ]
